application: kurzycnb
version: 1
runtime: python27
api_version: 1
threadsafe: true

inbound_services:

builtins:
- deferred: on
- appstats: on

skip_files:
- ^(.*)\.komodoproject$
- ^(.*)pyc$
- README.md
- LICENSE

handlers:
- url: /index.html(.*)
  static_files: pages/index.html
  upload: pages/index.html
- url: /favicon.ico
  static_files: pages/favicon.ico
  upload: pages/favicon.ico
- url: /static
  static_dir: pages
- url: /.*
  script: kurzycnb.app
